= Flow control


== The switch statement

- Example:

[source,java]
----
class TestSwitch {
public static void main(String[] args){
 int month = 8;
String monthString;
switch (month) {
    case 1:  monthString = "January";
             break;
    case 2:  monthString = "February";
             break;
    case 3:  monthString = "March";
             break;
    case 4:  monthString = "April";
             break;
    case 5:  monthString = "May";
             break;
    case 6:  monthString = "June";
             break;
    case 7:  monthString = "July";
             break;
    case 8:  monthString = "August";
             break;
    case 9:  monthString = "September";
             break;
    case 10: monthString = "October";
             break;
    case 11: monthString = "November";
             break;
    case 12: monthString = "December";
             break;
    default: monthString = "Invalid month";
             break;
}

System.out.println(monthString);

}

}
----

=== Supported switch types
- The following types can be used in a switch statement:
- int and Integer
- byte and Byte
- short and Short
- char and Character
- String
- enum values
- var

=== Value in the case statement
- The value of the constant statement must be a literal or a final variable and must be of the same data type as the variable in the switch.

== Switch expression
- The switch expression is a new feature in Java 12.
- It is a simplified version of the switch statement.
- It is a statement that evaluates to a value.
- It is used in the switch statement.
- example:
[source,java]
----
public class TestSwitchExpression {
    public static void main(String[] args) {
        int month = 8;
        String monthString = switch (month) {
            case 1 -> "January";
            case 2 -> "February";
            case 3 -> "March";
            case 4 -> "April";
            case 5 -> "May";
            case 6 -> "June";
            case 7 -> "July";
            case 8 -> "August";
            case 9 -> "September";
            case 10 -> "October";
            case 11 -> "November";
            case 12 -> "December";
            default -> "Invalid month";
        };
        System.out.println(monthString);
    }
}
----

=== Rules of the switch expression
- if the switch statement returns a value, then all branches that don't throw an exception must return a value with the same data type.
- if the expression returns a value, then branches that aren't expressions must yield a result.
- default branch is required if the switch expression is not exhaustive.

=== Case block vs case expression
